### ISSUE TITLE
Soundscapy cannot be installed on Colab

### ISSUE THREAD

**Issue by karnwatcharasupat** [MitchellAcoustics/Soundscapy#59]
Colab environment (from `uname -a`): 
> Linux a3fd98b3f4fa 5.4.188+ #1 SMP Sun Apr 24 10:03:06 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux

Error message:
> Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement soundscapy (from versions: none)
ERROR: No matching distribution found for soundscapy

Python version: 3.7.13

Issue is likely due to the package only supporting the newly released Python 3.10.

**Comment by MitchellAcoustics** [comment]
Hi Karn, thanks for raising this. Yeah, that seems reasonable. I was planning to check out if I can downgrade the Python requirement anyway, so I'll push this to the top.

**Comment by MitchellAcoustics** [comment]
The python version has now been downgraded to Python >= 3.7 and published to PyPI as v0.3.6. In my test it now works fine on Google colab.

**Comment by MitchellAcoustics** [comment]
Downgraded soundscapy works on 3.7 and Colab, but now Numpy conflicts with higher versions of Python. Confirmed not to work on Python 3.10 with error: `ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

@MitchellAcoustics to investigate dependency errors and adjust

**Comment by MitchellAcoustics** [comment]
Dependency errors solved in #60 with PyPI release 0.3.8.  Confirmed to install correctly on Python 3.7 and 3.10 on both Linux and Windows and to still install correctly on Google Colab. I'd eventually like to drop support for 3.7, but it still makes sense to support Google colab so until they upgrade their python version, I'll have to keep it I think.
