### ISSUE TITLE
1048: WavFileWarning: Chunk (non-data) not understood, skipping it.

### ISSUE THREAD

**Issue by balandinodidonato** [MitchellAcoustics/Soundscapy#73]
I'm following the tutorial using my own recordings.
After loading the levels, I carried on with loading the WAV files, and I got this error:
`1048: WavFileWarning: Chunk (non-data) not understood, skipping it.`

as in 5 -> https://github.com/MitchellAcoustics/Soundscapy/blob/main/docs/tutorials/BinauralAnalysis.ipynb

Any advice?

**Comment by MitchellAcoustics** [comment]
I haven't come across this error before. It doesn't come from Soundscapy itself, but from the underlying libraries used to load wavfiles (scipy in this case, I think). My suspicion is that you have some additional metadata in the wav file that isn't recognised by scipy. See this blog post: https://saturncloud.io/blog/getting-started-with-scipyiowavfile-fixing-the-wavfilewarning-chunk-not-understood-error/

Is this just a warning and you're still able to load the WAV data, or does this prevent you from loading at all?

**Comment by balandinodidonato** [comment]
It prevents from loading it at all.

**Comment by MitchellAcoustics** [comment]
Soundscapy does not implement the WAV loading itself. We rely on the `Signal` class from [Python Acoustics](https://github.com/python-acoustics/python-acoustics/tree/master), which uses `scipy.io.wavfile.read()`. That's where this error comes from and there's not much we can do in Soundscapy to address it directly. 

Some options to resolve it are given in the blog post above. You could also bypass our native load function and use a different package for loading the WAV file to a numpy array then pass that to Soundscapy. Here's an option using librosa:

```
from soundscapy import Binaural
import librosa

y, fs = librosa.load("path_to_wav_file.wav", mono = False)
b = Binaural(y, fs)
```

I've confirmed this works with our example WAV files, but it may still fail if your WAV file is corrupted. librosa doesn't use scipy under the hood, so they may have a better way of resolving the metadata. You could do a similar thing with pydub or wave as well.
