### ISSUE TITLE
Requirement for sampling frequency of 48kHz from mosqito dependency

### ISSUE THREAD

**Issue by auraacustica** [MitchellAcoustics/Soundscapy#79]
When trying to calculate loudness using Mosqito dependency an error ocurred demanding 48kHz sampling frequency: 

![image](https://github.com/user-attachments/assets/c23ee439-be53-4ee9-838d-8be4dcbe0345)

**Comment by MitchellAcoustics** [comment]
I added a resampling option throughout the file processing interface. When loading a wav file with e.g. `Binaural.from_wav()` you can now set `resample = 48000` to ensure it is set up correctly for Mosqito. The same has been carried through to `AudioAnalysis` functions. Resolved in commit 6b720780e27b9552f4ebe7885c4ee73a558f2009
